# Generated by Django 5.1.7 on 2025-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False, verbose_name='薪资编号')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本工资')),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最终工资')),
                ('deduction_days', models.IntegerField(verbose_name='扣除天数')),
                ('leave_days', models.IntegerField(verbose_name='请假天数')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '薪资信息',
                'verbose_name_plural': '薪资信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
