# Generated by Django 5.1.7 on 2025-04-24 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_manager',
            field=models.ForeignKey(default=22001, limit_choices_to={'emp_role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='dept_manager', to=settings.AUTH_USER_MODEL, verbose_name='部门经理'),
            preserve_default=False,
        ),
    ]
