# Generated by Django 5.1.7 on 2025-04-28 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_dept_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'emp_role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_manager', to=settings.AUTH_USER_MODEL, verbose_name='部门经理'),
        ),
    ]
