# Generated by Django 5.1.7 on 2025-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='考勤编号')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('status', models.CharField(choices=[('normal', '正常打卡'), ('leave', '请假'), ('absent', '缺勤')], max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '考勤信息',
                'verbose_name_plural': '考勤信息',
            },
        ),
    ]
