# Generated by Django 5.1.7 on 2025-04-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_emp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='考勤编号'),
        ),
    ]
