# Generated by Django 5.1.7 on 2025-04-29 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_attendance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('normal', '正常打卡'), ('leave', '请假'), ('absent', '缺勤'), ('late', '迟到')], max_length=10, verbose_name='状态'),
        ),
    ]
